### ISSUE TITLE
Unhandled rejection TypeError: this.offline.push is not a function

### ISSUE THREAD

**Issue by arkeros** [pixelcanvasio/pixelcanvas#1]
0|web      | 2017-09-11 09:54:52 +00:00: Unhandled rejection TypeError: this.offline.push is not a function
0|web      |     at Publisher.publish (/home/pixel/www/web.js:3328:20)
0|web      |     at broadcast (/home/pixel/www/web.js:3388:13)
0|web      |     at /home/pixel/www/web.js:978:94
0|web      |     at next (native)
0|web      |     at step (/home/pixel/www/web.js:1005:191)
0|web      |     at /home/pixel/www/web.js:1005:361
0|web      |     at wrapped (/home/pixel/www/node_modules/newrelic/lib/transaction/tracer/index.js:182:28)
0|web      |     at wrappedPromise.linkTransaction (/home/pixel/www/node_modules/newrelic/lib/instrumentation/promise.js:297:65)
0|web      |     at wrappedPromise.wrapped (/home/pixel/www/node_modules/newrelic/lib/transaction/tracer/index.js:182:28)
0|web      |     at __NR_wrappedThenHandler (/home/pixel/www/node_modules/newrelic/lib/instrumentation/promise.js:473:26)

**Comment by arkeros** [comment]
Probable related with 
0|web      | 2017-09-11 10:02:04 +00:00: error: [AMQP] connect EHOSTUNREACH 10.135.58.22:5672
